<?php
require '../libs/fpdf/fpdf.php';
include '../includes/db.php'; // Using $conn (mysqli)
require_once '../includes/auth.php';

// Only staff/admin can generate reports
requireAuth();

/* Read filters */
$selectedYear = $_GET['year'] ?? '';
$selectedMonth = $_GET['month'] ?? '';

$where = ["mb.paid = 1"]; 
$params = [];
$types = "";

if ($selectedYear) {
    $where[] = "YEAR(mb.bill_month) = ?";
    $params[] = $selectedYear;
    $types .= "i";
}

if ($selectedMonth) {
    $where[] = "MONTH(mb.bill_month) = ?";
    $params[] = $selectedMonth;
    $types .= "i";
}

$whereSql = "WHERE " . implode(" AND ", $where);

/* ===============================
    SQL FIXED: Pluralized Table Names
================================ */
$sql = "
SELECT 
    DATE_FORMAT(mb.bill_month, '%Y-%m') AS raw_period,
    SUM(
        rt.base_room_fee +
        ((mb.new_electric - mb.old_electric) * ur.electric_rate) +
        (mb.water_units * ur.water_rate)
    ) AS income
FROM monthly_bills mb
JOIN rooms rm ON mb.room_id = rm.room_id
JOIN room_types rt ON rm.room_type_id = rt.room_type_id
JOIN utility_rates ur ON mb.rate_id = ur.rate_id
$whereSql
GROUP BY raw_period
ORDER BY raw_period DESC
";

$stmt = $conn->prepare($sql);
if (!empty($params)) {
    $stmt->bind_param($types, ...$params);
}
$stmt->execute();
$result = $stmt->get_result();
$data = $result->fetch_all(MYSQLI_ASSOC);

/* ===============================
    MODERN PDF UI GENERATION
================================ */
class PDF extends FPDF
{
    function Header()
    {
        // Dark Blue Header Bar
        $this->SetFillColor(15, 23, 42); // Navy Slate
        $this->Rect(0, 0, 210, 40, 'F');
        
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Arial', 'B', 18);
        $this->Cell(0, 15, 'PHNOM PENH PROPERTY', 0, 1, 'L');
        
        $this->SetFont('Arial', '', 10);
        $this->Cell(0, -5, 'Financial Revenue Intelligence Report', 0, 1, 'L');
        
        $this->SetY(15);
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 10, 'INCOME REPORT', 0, 1, 'R');
        $this->Ln(20);
    }

    function Footer()
    {
        $this->SetY(-20);
        $this->SetFont('Arial', 'I', 8);
        $this->SetTextColor(150, 150, 150);
        $this->Cell(0, 10, 'This report is generated automatically by the Room Rental System.', 0, 0, 'L');
        $this->Cell(0, 10, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'R');
    }
}

$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetMargins(15, 15, 15);
$pdf->Ln(10);

// Summary Info Box
$subtitle = 'ALL TIME RECORDS';
if ($selectedYear && $selectedMonth) {
    $subtitle = date('F', mktime(0, 0, 0, $selectedMonth)) . " $selectedYear";
} elseif ($selectedYear) {
    $subtitle = "ANNUAL REPORT - $selectedYear";
}

$pdf->SetTextColor(50, 50, 50);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(40, 7, 'REPORT PERIOD:', 0, 0);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(0, 7, strtoupper($subtitle), 0, 1);

$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(40, 7, 'GENERATED BY:', 0, 0);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(0, 7, strtoupper($_SESSION['user']['username'] ?? 'Admin'), 0, 1);
$pdf->Ln(10);

/* Modern Table */
$pdf->SetDrawColor(220, 230, 240);
$pdf->SetFillColor(245, 247, 251); // Soft Blue Header
$pdf->SetTextColor(30, 41, 59);
$pdf->SetFont('Arial', 'B', 11);

// Table Header
$pdf->Cell(100, 12, 'Billing Period (Month/Year)', 1, 0, 'L', true);
$pdf->Cell(80, 12, 'Revenue Amount (USD)', 1, 1, 'R', true);

// Table Rows
$pdf->SetFont('Arial', '', 11);
$totalIncome = 0;
$fill = false;

foreach ($data as $row) {
    $formattedPeriod = date('F Y', strtotime($row['raw_period'] . "-01"));
    
    $pdf->SetFillColor(255, 255, 255);
    if($fill) $pdf->SetFillColor(250, 252, 255); // Alternating row color
    
    $pdf->Cell(100, 10, $formattedPeriod, 1, 0, 'L', true);
    $pdf->Cell(80, 10, '$ ' . number_format($row['income'], 2), 1, 1, 'R', true);
    
    $totalIncome += $row['income'];
    $fill = !$fill;
}

/* Grand Total Section */
$pdf->Ln(5);
$pdf->SetFillColor(37, 99, 235); // Success Blue
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(100, 14, 'TOTAL ACCUMULATED REVENUE', 0, 0, 'R');
$pdf->Cell(80, 14, '$ ' . number_format($totalIncome, 2), 0, 1, 'R', true);

/* Final Signature/Stamp Area */
$pdf->Ln(30);
$pdf->SetTextColor(50, 50, 50);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(120);
$pdf->Cell(60, 5, 'Authorized Signature', 0, 1, 'C');
$pdf->Ln(15);
$pdf->Cell(120);
$pdf->Cell(60, 0.1, '', 1, 1); // Signature line
$pdf->SetFont('Arial', '', 8);
$pdf->Cell(120);
$pdf->Cell(60, 5, 'Phnom Penh Property Admin Office', 0, 1, 'C');

$pdf->Output('I', 'Revenue_Report_' . date('Ymd') . '.pdf');